- name: Install and configure MariaDB
  hosts: all
  become: yes
      
  tasks:
    - name: Update apt package
      apt:
        update_cache: yes  
        
    - name: Install required packages
      apt:
        name:
          - unzip
          - mariadb-server
          - mariadb-client
        state: present

    - name: Start and enable MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes


     
